export const typesOptionsPokemon = [
  { text: 'NORMAL', value: 'NORMAL' },
  { text: 'inseto', value: 'inseto' },
  { text: 'sombrio', value: 'sombrio' },
  { text: 'dragão', value: 'dragão' },
  { text: 'elétrico', value: 'elétrico' },
  { text: 'lutador', value: 'lutador' },
  { text: 'fogo', value: 'fogo' },
  { text: 'voador', value: 'voador' },
  { text: 'fantasma', value: 'fantasma' },
  { text: 'planta', value: 'planta' },
  { text: 'terra', value: 'terra' },
  { text: 'gelo', value: 'gelo' },
  { text: 'veneno', value: 'veneno' },
  { text: 'psíquico', value: 'psíquico' },
  { text: 'pedra', value: 'pedra' },
  { text: 'metálico', value: 'metálico' },
  { text: 'água', value: 'água' },
];
