export const typesOptionsPokemon = [
  { value: 'normal', text: 'normal' },
  { value: 'bug', text: 'inseto' },
  { value: 'dark', text: 'sombrio' },
  { value: 'dragon', text: 'dragão' },
  { value: 'electric', text: 'elétrico' },
  { value: 'fighting', text: 'lutador' },
  { value: 'fire', text: 'fogo' },
  { value: 'flying', text: 'voador' },
  { value: 'ghost', text: 'fantasma' },
  { value: 'grass', text: 'planta' },
  { value: 'ground', text: 'terra' },
  { value: 'ice', text: 'gelo' },
  { value: 'poison', text: 'veneno' },
  { value: 'psychic', text: 'psíquico' },
  { value: 'rock', text: 'pedra' },
  { value: 'steel', text: 'metálico' },
  { value: 'water', text: 'água' },
  { value: 'fairy', text: 'fada' },
];
